/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/girls/': RouteRecordInfo<'/girls/', '/girls', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/CloudComputer/Fusion-make-computer': RouteRecordInfo<'/posts/CloudComputer/Fusion-make-computer', '/posts/CloudComputer/Fusion-make-computer', Record<never, never>, Record<never, never>>,
    '/posts/CloudComputer/horizon-ad': RouteRecordInfo<'/posts/CloudComputer/horizon-ad', '/posts/CloudComputer/horizon-ad', Record<never, never>, Record<never, never>>,
    '/posts/CloudComputer/horizon-ad-dns': RouteRecordInfo<'/posts/CloudComputer/horizon-ad-dns', '/posts/CloudComputer/horizon-ad-dns', Record<never, never>, Record<never, never>>,
    '/posts/CloudComputer/horizon-insall-sql': RouteRecordInfo<'/posts/CloudComputer/horizon-insall-sql', '/posts/CloudComputer/horizon-insall-sql', Record<never, never>, Record<never, never>>,
    '/posts/CloudComputer/horizon-install-composer': RouteRecordInfo<'/posts/CloudComputer/horizon-install-composer', '/posts/CloudComputer/horizon-install-composer', Record<never, never>, Record<never, never>>,
    '/posts/CloudComputer/HorizonAgent': RouteRecordInfo<'/posts/CloudComputer/HorizonAgent', '/posts/CloudComputer/HorizonAgent', Record<never, never>, Record<never, never>>,
    '/posts/CloudComputer/install-Compute': RouteRecordInfo<'/posts/CloudComputer/install-Compute', '/posts/CloudComputer/install-Compute', Record<never, never>, Record<never, never>>,
    '/posts/CloudComputer/install-connection': RouteRecordInfo<'/posts/CloudComputer/install-connection', '/posts/CloudComputer/install-connection', Record<never, never>, Record<never, never>>,
    '/posts/CloudComputer/install-EXSI': RouteRecordInfo<'/posts/CloudComputer/install-EXSI', '/posts/CloudComputer/install-EXSI', Record<never, never>, Record<never, never>>,
    '/posts/CloudComputer/install-omv': RouteRecordInfo<'/posts/CloudComputer/install-omv', '/posts/CloudComputer/install-omv', Record<never, never>, Record<never, never>>,
    '/posts/CloudComputer/install-VCSA': RouteRecordInfo<'/posts/CloudComputer/install-VCSA', '/posts/CloudComputer/install-VCSA', Record<never, never>, Record<never, never>>,
    '/posts/CloudComputer/install-windows-server': RouteRecordInfo<'/posts/CloudComputer/install-windows-server', '/posts/CloudComputer/install-windows-server', Record<never, never>, Record<never, never>>,
    '/posts/CloudComputer/installFusionAccess': RouteRecordInfo<'/posts/CloudComputer/installFusionAccess', '/posts/CloudComputer/installFusionAccess', Record<never, never>, Record<never, never>>,
    '/posts/CloudComputer/VCSA-to-AD': RouteRecordInfo<'/posts/CloudComputer/VCSA-to-AD', '/posts/CloudComputer/VCSA-to-AD', Record<never, never>, Record<never, never>>,
    '/posts/CloudComputer/what-is horizon': RouteRecordInfo<'/posts/CloudComputer/what-is horizon', '/posts/CloudComputer/what-is horizon', Record<never, never>, Record<never, never>>,
    '/posts/CloudComputer/what-is-Fusion': RouteRecordInfo<'/posts/CloudComputer/what-is-Fusion', '/posts/CloudComputer/what-is-Fusion', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/Troubles/安装FNOS': RouteRecordInfo<'/posts/Troubles/安装FNOS', '/posts/Troubles/安装FNOS', Record<never, never>, Record<never, never>>,
    '/posts/Troubles/try-fydeos': RouteRecordInfo<'/posts/Troubles/try-fydeos', '/posts/Troubles/try-fydeos', Record<never, never>, Record<never, never>>,
    '/posts/VPS/deploy-new-blog': RouteRecordInfo<'/posts/VPS/deploy-new-blog', '/posts/VPS/deploy-new-blog', Record<never, never>, Record<never, never>>,
    '/posts/VPS/use-bitwarden': RouteRecordInfo<'/posts/VPS/use-bitwarden', '/posts/VPS/use-bitwarden', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
